# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-23 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import oils.apps.circulation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('holding', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowingPrivillage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_limit', models.IntegerField(default=8)),
                ('loan_duration', models.IntegerField(default=20)),
                ('renewal_limit', models.IntegerField(default=3)),
                ('membership_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.MembershipType')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_at', models.DateTimeField(auto_now_add=True)),
                ('due_on', models.DateField(default=oils.apps.circulation.models.get_due_date)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holding.Item')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Patron')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRenewal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renew_at', models.DateTimeField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circulation.Loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='circulation.Loan')),
            ],
        ),
    ]
