# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('holding', '0001_initial'),
        ('circulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holding.ResourceInstance'),
        ),
    ]
