# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-04 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circulation', '0002_loan_item'),
        ('patron', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='patron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patron.Patron'),
        ),
    ]
