# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-12 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import oils.apps.circulation.models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0004_loan_due_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='due_on',
            field=models.DateField(default=oils.apps.circulation.models.get_due_date),
        ),
    ]
