# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-14 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0008_auto_20161012_2104'),
        ('circulation', '0005_auto_20161012_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowingPrivillage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_limit', models.IntegerField(default=8)),
                ('loan_duration', models.IntegerField(default=20)),
                ('renewal_limit', models.IntegerField(default=3)),
                ('membership_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patron.MembershipType')),
            ],
        ),
    ]
