# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-04 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0002_patron_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patron',
            name='identification',
        ),
    ]
