# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-30 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0003_remove_patron_identification'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_at', models.DateTimeField(blank=True, null=True)),
                ('expire_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatronIdentification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=60)),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patron.IdentificationType')),
            ],
        ),
        migrations.AddField(
            model_name='patron',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patron',
            name='contact',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='patronidentification',
            name='patron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patron.Patron'),
        ),
        migrations.AddField(
            model_name='membership',
            name='membership_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patron.MembershipType'),
        ),
        migrations.AddField(
            model_name='membership',
            name='patron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patron.Patron'),
        ),
    ]
