# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-10 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0006_auto_20160830_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patronidentification',
            name='patron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifications', to='patron.Patron'),
        ),
    ]
