# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-12 21:04
from __future__ import unicode_literals

from django.db import migrations, models

def binarized(apps, schema_editor):
    Patron = apps.get_model("patron", "Patron")
    for patron in Patron.objects.all():
        patron.notification_type = "7"
        patron.save()

class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0007_auto_20161010_2031'),
    ]

    operations = [
        migrations.RunPython(binarized),
        migrations.AlterField(
            model_name='patron',
            name='notification_type',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
