# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-17 00:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0008_auto_20161012_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patron',
            name='id',
        ),
        migrations.AlterField(
            model_name='patron',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
