# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0002_loan_resource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='resource',
            new_name='item',
        ),
    ]
