# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='AuthorAlias',
            new_name='AgentAlias',
        ),
        migrations.RenameModel(
            old_name='AuthorIdentifier',
            new_name='AgentIdentifier',
        ),
        migrations.RenameModel(
            old_name='AuthorIdentifierType',
            new_name='AgentIdentifierType',
        ),
        migrations.RemoveField(
            model_name='author',
            name='identifiers',
        ),
        migrations.RemoveField(
            model_name='agentalias',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AlterField(
            model_name='book',
            name='classifications',
            field=models.ManyToManyField(blank=True, to='catalog.Classification'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishers',
            field=models.ManyToManyField(blank=True, through='catalog.Publication', to='catalog.Publisher'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='catalog.Subject'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='bookagent',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Book'),
        ),
        migrations.AddField(
            model_name='bookagent',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Role'),
        ),
        migrations.AddField(
            model_name='agent',
            name='identifiers',
            field=models.ManyToManyField(to='catalog.AgentIdentifier'),
        ),
        migrations.AddField(
            model_name='agentalias',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Agent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='agents',
            field=models.ManyToManyField(blank=True, through='catalog.BookAgent', to='catalog.Agent'),
        ),
    ]
