# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-19 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='subject',
            managers=[
            ],
        ),
    ]
