# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20160620_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='identifiers',
            field=models.ManyToManyField(blank=True, to='catalog.AgentIdentifier'),
        ),
    ]
