# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20160621_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookUniqueIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Book')),
            ],
        ),
        migrations.RemoveField(
            model_name='bookidentifier',
            name='book',
        ),
        migrations.AddField(
            model_name='bookuniqueidentifier',
            name='identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.BookIdentifier'),
        ),
        migrations.AddField(
            model_name='bookidentifier',
            name='books',
            field=models.ManyToManyField(related_name='identifiers', through='catalog.BookUniqueIdentifier', to='catalog.Book'),
        ),
    ]
