# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20160705_0519'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversalIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=16)),
            ],
        ),
        migrations.RenameModel(
            old_name='BookIdentifierType',
            new_name='UniversalIdentifierType',
        ),
        migrations.RemoveField(
            model_name='bookuniqueidentifier',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookuniqueidentifier',
            name='identifier',
        ),
        migrations.AddField(
            model_name='bookidentifier',
            name='book',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='catalog.Book'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='bookidentifier',
            unique_together=set([]),
        ),
        migrations.AddField(
            model_name='universalidentifier',
            name='id_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.UniversalIdentifierType'),
        ),
        migrations.RemoveField(
            model_name='bookidentifier',
            name='books',
        ),
        migrations.RemoveField(
            model_name='bookidentifier',
            name='id_type',
        ),
        migrations.RemoveField(
            model_name='bookidentifier',
            name='value',
        ),
        migrations.AddField(
            model_name='book',
            name='identifiers',
            field=models.ManyToManyField(through='catalog.BookIdentifier', to='catalog.UniversalIdentifier'),
        ),
        migrations.AddField(
            model_name='bookidentifier',
            name='identifier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.UniversalIdentifier'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BookUniqueIdentifier',
        ),
        migrations.AlterUniqueTogether(
            name='universalidentifier',
            unique_together=set([('id_type', 'value')]),
        ),
    ]
