# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20160706_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='last_name',
        ),
        migrations.AddField(
            model_name='agent',
            name='full_name',
            field=models.CharField(default='-', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='identifiers',
            field=models.ManyToManyField(related_name='books', through='catalog.BookIdentifier', to='catalog.UniversalIdentifier'),
        ),
    ]
