# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20160708_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='place',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
