# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_publication_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
