# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20160710_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='place',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
