# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20160710_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Publisher'),
        ),
    ]
